window.FISH_PHOTOS = {
  bungeo: { file: 'img/fish/bungeo.jpg', license: 'cc-by', author: 'Yung-Lun Lin', source: 'https://www.inaturalist.org/photos/298291677' },
  ingeo: { file: 'img/fish/ingeo.jpg', license: 'cc0', author: 'sunny tyson', source: 'https://www.inaturalist.org/photos/316892261' },
  bluegill: { file: 'img/fish/bluegill.jpg', license: 'cc-by', author: 'Joshua Johnson', source: 'https://www.inaturalist.org/photos/549859103' },
  bass: { file: 'img/fish/bass.jpg', license: 'cc-by', author: 'sudomir', source: 'https://www.inaturalist.org/photos/31909164' },
  ssogari: { file: 'img/fish/ssogari.jpg', license: 'cc-by-nc', author: 'Seokin Yang', source: 'https://www.inaturalist.org/photos/202896417' },
  kkeuri: { file: 'img/fish/kkeuri.jpg', license: 'cc-by-nc', author: 'r-fujii', source: 'https://www.inaturalist.org/photos/597353172' },
  megi: { file: 'img/fish/megi.jpg', license: 'cc-by', author: 'Hawk T.', source: 'https://www.inaturalist.org/photos/405690961' },
  songeo: { file: 'img/fish/songeo.jpg', license: 'cc-by', author: 'mnauky', source: 'https://www.inaturalist.org/photos/577647406' },
  pike: { file: 'img/fish/pike.jpg', license: 'cc-by-sa', author: 'Ewout Knoester', source: 'https://www.inaturalist.org/photos/550345828' },
  walleye: { file: 'img/fish/walleye.jpg', license: 'cc-by', author: 'Quinn', source: 'https://www.inaturalist.org/photos/363833874' },
  chcat: { file: 'img/fish/chcat.jpg', license: 'cc0', author: 'David Emmanuel', source: 'https://www.inaturalist.org/photos/585086071' },
  char: { file: 'img/fish/char.jpg', license: 'cc-by', author: 'Alison Copeland', source: 'https://www.inaturalist.org/photos/311639131' },
  salmon: { file: 'img/fish/salmon.jpg', license: 'cc-by', author: 'Matt Bowser', source: 'https://www.inaturalist.org/photos/4105218' },
  peacock: { file: 'img/fish/peacock.jpg', license: 'cc-by-sa', author: 'Ong Jyh Seng', source: 'https://www.inaturalist.org/photos/185311182' },
  piranha: { file: 'img/fish/piranha.jpg', license: 'cc-by', author: 'Diogo Luiz', source: 'https://www.inaturalist.org/photos/599891387' },
  arowana: { file: 'img/fish/arowana.jpg', license: 'cc0', author: 'w_endo', source: 'https://www.inaturalist.org/photos/205177566' },
  tilapia: { file: 'img/fish/tilapia.jpg', license: 'cc0', author: 'Richard Fuller', source: 'https://www.inaturalist.org/photos/597869107' },
  nileperch: { file: 'img/fish/nileperch.jpg', license: 'cc-by-nc', author: 'Fish and Benthos survey Chinko', source: 'https://www.inaturalist.org/photos/150012973' },
  eel: { file: 'img/fish/eel.jpg', license: 'cc-by', author: '如此甚好', source: 'https://www.inaturalist.org/photos/428087998' },
  snakehead: { file: 'img/fish/snakehead.jpg', license: 'cc-by', author: 'Nicola Crockford', source: 'https://www.inaturalist.org/photos/451045982' },
  sturgeon: { file: 'img/fish/sturgeon.jpg', license: 'cc-by', author: 'Brodie Cass Talbott', source: 'https://www.inaturalist.org/photos/28129281' },
  arapaima: { file: 'img/fish/arapaima.jpg', license: 'cc-by', author: 'Vincent A. Vos', source: 'https://www.inaturalist.org/photos/39430627' },
  musky: { file: 'img/fish/musky.jpg', license: 'cc-by', author: 'Dan MacNeal', source: 'https://www.inaturalist.org/photos/558217618' },
  ureok: { file: 'img/fish/ureok.jpg', license: 'cc-by-sa', author: 'Wensen Wang', source: 'https://www.inaturalist.org/photos/691293960' },
  gwangeo: { file: 'img/fish/gwangeo.jpg', license: 'cc-by-nc', author: 'H.T.Cheng', source: 'https://www.inaturalist.org/photos/3540735' },
  chamdom: { file: 'img/fish/chamdom.jpg', license: 'cc-by', author: 'Peter Chen 2.0', source: 'https://www.inaturalist.org/photos/364265922' },
  nongeo: { file: 'img/fish/nongeo.jpg', license: 'cc-by-nc', author: 'fzwkq', source: 'https://www.inaturalist.org/photos/493597030' },
  gamseong: { file: 'img/fish/gamseong.jpg', license: 'cc-by-sa', author: 'Luke', source: 'https://www.inaturalist.org/photos/419820543' },
  godeungeo: { file: 'img/fish/godeungeo.jpg', license: 'cc0', author: 'Al Kordesch', source: 'https://www.inaturalist.org/photos/382789264' },
  gt: { file: 'img/fish/gt.jpg', license: 'cc-by-sa', author: 'Robert Webster', source: 'https://www.inaturalist.org/photos/56596089' },
  barracuda: { file: 'img/fish/barracuda.jpg', license: 'cc-by', author: 'Dan Schofield', source: 'https://www.inaturalist.org/photos/459229520' },
  grouper: { file: 'img/fish/grouper.jpg', license: 'cc-by-nc', author: 'ri_su', source: 'https://www.inaturalist.org/photos/630312566' },
  mahi: { file: 'img/fish/mahi.jpg', license: 'cc-by', author: 'Nick Tobler (Cowturtle)', source: 'https://www.inaturalist.org/photos/540579538' },
  parrot: { file: 'img/fish/parrot.jpg', license: 'cc-by', author: 'Julien Renoult', source: 'https://www.inaturalist.org/photos/7743026' },
  snapper: { file: 'img/fish/snapper.jpg', license: 'cc-by-sa', author: 'tobyyy', source: 'https://www.inaturalist.org/photos/110984379' },
  cod: { file: 'img/fish/cod.jpg', license: 'cc-by', author: 'Julien Savoie', source: 'https://www.inaturalist.org/photos/440775607' },
  halibut: { file: 'img/fish/halibut.jpg', license: 'cc-by', author: 'Julien Savoie', source: 'https://www.inaturalist.org/photos/568780146' },
  pollock: { file: 'img/fish/pollock.jpg', license: 'cc-by', author: 'Ted Cheeseman', source: 'https://www.inaturalist.org/photos/368073866' },
  conger: { file: 'img/fish/conger.jpg', license: 'cc-by-nc', author: 'taiwan_habu', source: 'https://www.inaturalist.org/photos/586564639' },
  bangeo: { file: 'img/fish/bangeo.jpg', license: 'cc-by-nc', author: '@Danilabirdwatcher', source: 'https://www.inaturalist.org/photos/597467728' },
  tuna: { file: 'img/fish/tuna.jpg', license: 'cc-by-nc', author: 'brock', source: 'https://www.inaturalist.org/photos/237808389' },
  sailfish: { file: 'img/fish/sailfish.jpg', license: 'cc-by', author: 'Navaneeth Sini George', source: 'https://www.inaturalist.org/photos/459954919' },
  moray: { file: 'img/fish/moray.jpg', license: 'cc0', author: 'Jean-Paul Boerekamps', source: 'https://www.inaturalist.org/photos/168348870' },
  mako: { file: 'img/fish/mako.jpg', license: 'cc-by', author: 'Fábio Olmos', source: 'https://www.inaturalist.org/photos/74638241' },
  blacktip: { file: 'img/fish/blacktip.jpg', license: 'cc-by', author: 'Abbie King', source: 'https://www.inaturalist.org/photos/29645867' },
  hammerhead: { file: 'img/fish/hammerhead.jpg', license: 'cc-by', author: 'Daniel Z', source: 'https://www.inaturalist.org/photos/349411180' },
  mola: { file: 'img/fish/mola.jpg', license: 'cc-by', author: 'Dirk Froebel', source: 'https://www.inaturalist.org/photos/289315754' },
  whaleshark: { file: 'img/fish/whaleshark.jpg', license: 'cc-by', author: 'Jeremy Jones', source: 'https://www.inaturalist.org/photos/452166632' },
  manta: { file: 'img/fish/manta.jpg', license: 'cc-by-sa', author: 'Ewout Knoester', source: 'https://www.inaturalist.org/photos/476241119' },
  turtle: { file: 'img/fish/turtle.jpg', license: 'cc-by', author: 'James Hardcastle', source: 'https://www.inaturalist.org/photos/23578828' },
  dolphin: { file: 'img/fish/dolphin.jpg', license: 'cc0', author: 'bdhimes', source: 'https://www.inaturalist.org/photos/706089380' },
  humpback: { file: 'img/fish/humpback.jpg', license: 'cc-by', author: 'Bill Levine', source: 'https://www.inaturalist.org/photos/250423633' },
  orca: { file: 'img/fish/orca.jpg', license: 'cc-by', author: 'Dan Riley', source: 'https://www.inaturalist.org/photos/107738894' }
};
